#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)
if [ $branch == main ]
then
  if [ -z $gh_push ]
  then
    echo "Deploying to gh-pages..."
    gh_push=1
    git subtree push --prefix output origin gh-pages
  else
    unset gh_push
  fi
fi
exit