#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" == main ]
then
  if [ -e .push ]
  then
    rm .push
  else
    echo "Deploying to gh-pages..."
    touch .push
    git subtree push --prefix output origin gh-pages
  fi
fi
exit